# 1. Importing Libraries and Datasets

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/amazon_ecommerce_1M.csv")
df.head()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43,71,S2679,4.3,2025-03-04,6,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13,119,S9279,4.9,2025-12-12,1,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46,229,S5557,4.9,2024-04-25,1,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6,52,S2519,3.1,2025-12-18,2,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48,274,S3045,2.6,2024-05-16,5,Delhi,Web,UPI,False,Delayed

# 2. Data Understanding and Data Cleaning

In [ ]:
df.describe()

,price,discount,final_price,rating,review_count,stock,seller_rating,shipping_time_days
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,13224.119093,28.996161,9938.876985,3.927226,32.626704,250.023345,3.750030,3.166389
std,18079.626921,14.681077,14271.885557,0.519443,43.382201,144.567038,0.722092,1.674178
min,200.030000,5.000000,101.460000,1.500000,0.000000,0.000000,2.500000,1.000000
25%,2700.147500,16.910000,1705.930000,3.600000,10.000000,125.000000,3.100000,2.000000
50%,4971.830000,28.070000,3790.795000,3.900000,20.000000,250.000000,3.800000,3.000000
75%,14134.482500,39.240000,10384.440000,4.300000,39.000000,375.000000,4.400000,5.000000
max,79999.700000,70.000000,75831.110000,5.000000,3408.000000,500.000000,5.000000,6.000000

In [ ]:
# Check missing values
df.isna().sum()

user_id               0
product_id            0
category              0
subcategory           0
brand                 0
price                 0
discount              0
final_price           0
rating                0
review_count          0
stock                 0
seller_id             0
seller_rating         0
purchase_date         0
shipping_time_days    0
location              0
device                0
payment_method        0
is_returned           0
delivery_status       0
dtype: int64

In [ ]:
# Check duplicated data
df.duplicated().sum()

np.int64(0)

In [ ]:
# Standardize number writings
df['price'] = df['price'].round(2)
df['discount'] = df['discount'].round(2)
df['final_price'] = df['final_price'].round(2)
df['rating'] = df['rating'].round(1)
df['seller_rating'] = df['seller_rating'].round(1)
df.head()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43,71,S2679,4.3,2025-03-04,6,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13,119,S9279,4.9,2025-12-12,1,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46,229,S5557,4.9,2024-04-25,1,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6,52,S2519,3.1,2025-12-18,2,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48,274,S3045,2.6,2024-05-16,5,Delhi,Web,UPI,False,Delayed

In [ ]:
# Fix inconsistencies in final prices
df['expected_final'] = df['price'] * (1 - df['discount'] / 100)
df['price_mismatch'] = (df['final_price'] - df['expected_final']).abs() > 1
# Decision: recalculate final_price or flag these rows
df['final_price'] = df['expected_final'].round(2)
df.head()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,...,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status,expected_final,price_mismatch
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.24,4.9,43,...,4.3,2025-03-04,6,Bangalore,Tablet,UPI,True,Returned,29629.242654,False
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.54,3.9,13,...,4.9,2025-12-12,1,Delhi,Tablet,UPI,True,Returned,8870.540796,False
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10920.07,4.2,46,...,4.9,2024-04-25,1,Chennai,Mobile App,Credit Card,True,Returned,10920.069000,False
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.89,3.8,6,...,3.1,2025-12-18,2,Mumbai,Web,UPI,False,In Transit,502.893277,False
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.72,4.0,48,...,2.6,2024-05-16,5,Delhi,Web,UPI,False,Delayed,5589.718673,False

In [ ]:
# Count item with zero in stock
zero_stock = df[df['stock'] == 0]
len(zero_stock)

2003

In [ ]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'])

In [ ]:
df['location'] = df['location'].str.strip().str.title()
df.head()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,...,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status,expected_final,price_mismatch
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.24,4.9,43,...,4.3,2025-03-04,6,Bangalore,Tablet,UPI,True,Returned,29629.242654,False
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.54,3.9,13,...,4.9,2025-12-12,1,Delhi,Tablet,UPI,True,Returned,8870.540796,False
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10920.07,4.2,46,...,4.9,2024-04-25,1,Chennai,Mobile App,Credit Card,True,Returned,10920.069000,False
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.89,3.8,6,...,3.1,2025-12-18,2,Mumbai,Web,UPI,False,In Transit,502.893277,False
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.72,4.0,48,...,2.6,2024-05-16,5,Delhi,Web,UPI,False,Delayed,5589.718673,False

Warning: Total number of columns (22) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.to_csv('amazon_ecommerce_cleaned.csv', index=False)
print("File 'amazon_ecommerce_cleaned.csv' has been created successfully.")

File 'amazon_ecommerce_cleaned.csv' has been created successfully.